version: "3.8"
services:
  database:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - database-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
  backend:
    build: ./src
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./.env.development
    depends_on:
      - database
volumes:
  data:
  logs:
